[project]
name = "icestream"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kio>=0.4.0",
    "psqlpy>=0.9.3",
    "structlog>=25.2.0",
]
