"""initial schema

Revision ID: c74436d2f2b2
Revises: 
Create Date: 2025-06-12 15:20:48.690157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c74436d2f2b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wal_files',
    sa.Column('s3_uri', sa.Text(), nullable=False),
    sa.Column('s3_etag', sa.Text(), nullable=True),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('compacted', sa.Boolean(), nullable=False),
    sa.Column('compacted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('compacted_by', sa.Text(), nullable=True),
    sa.Column('iceberg_commit_id', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partitions',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('partition_number', sa.Integer(), nullable=False),
    sa.Column('last_offset', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wal_file_offsets',
    sa.Column('wal_file_id', sa.BigInteger(), nullable=False),
    sa.Column('partition_id', sa.Integer(), nullable=False),
    sa.Column('base_offset', sa.BigInteger(), nullable=False),
    sa.Column('last_offset', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.ForeignKeyConstraint(['partition_id'], ['partitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wal_file_id'], ['wal_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('topics', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topics', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_table('wal_file_offsets')
    op.drop_table('partitions')
    op.drop_table('wal_files')
    # ### end Alembic commands ###
